### ISSUE TITLE
Add dependencies between tasks in the GitHub Actions

### ISSUE THREAD

**Issue by obervinov** [obervinov/users-package#13]
Adding dependencies between tasks (for fix errors [here](https://github.com/obervinov/vault-package/actions/runs/5043389834/jobs/9045115772) and [here](https://github.com/obervinov/vault-package/actions/runs/5043389834/jobs/9045115125))
_Maybe add to templates or specified workflow_
https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs
```yml
name: Create GitHub Release

on:
  push:
    branches: [main]
    paths: ['vault/**']

jobs:
  create-release:
    uses: obervinov/_templates/.github/workflows/create.release.yml@v1.0.4
    needs: [pylint, verify-package, verify-changelog, pytest]
```
