### ISSUE TITLE
GitHub Actions workflow updates: 2023.05.22

### ISSUE THREAD

**Issue by obervinov** [obervinov/users-package#6]
- [x] Add a filter to the release creation workflow to exclude the launch if the module files have not changed
```yml
name: Create GitHub Release

on:
  push:
    branches: [main]
    paths: ['users/**']

jobs:
  create-release:
    uses: obervinov/_templates/.github/workflows/create.release.yml@v1.0.4
```

- [x] Add workflow with package installation verification (by tag, branch, default)
```yml
  verify-package:
    uses: obervinov/_templates/.github/workflows/verify.package.yml@v1.0.4
```

- [x] Tests and checks workflow - run on the main branch for the show badge
```yml
name: Tests and Checks

on:
  push:
    branches:    
      - '*'
      - '*/*'
      - '**'
```

- [x] update the version of all workflows to https://github.com/obervinov/_templates/tree/v1.0.4
